# Site settings
title: Nafizyo Belajar NodeJS
email: phisnafis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog catatan belajar NodeJS, sebab terlalu susah mencari rujukan 
  Bahasa Melayu tajuk ini. Semua rencana merupakan pandangan peribadi saya,
  tapi semoga bermanfaat juga untuk semua pembaca. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog-nafizyo.netlify.app" # the base hostname & protocol for your site
twitter_username: nafizyo
github_username:  nafizyo

# Build settings
markdown: kramdown
